

orderdb:
  thread:
    read: 64
  disk:
    directory: orderdb
    scopeLimit: 8
  admin:
    checkPassword: false
    password: orderdb2018

jsonrpclite:
  sendTimeLimit: 2000
  bufferSizeLimit: 20000

server:
  port: 17711

