

orderdb:
  thread:
    read: 64
  disk:
    directory: orderdb
    scopeLimit: 8
  admin:
    checkPassword: false
    password: orderdb2018

websocket:
  client:
    sendTimeLimit: 2000
    bufferSizeLimit: 20000
  server:
    maxTextMessageBufferSize: 10485760
    maxBinaryMessageBufferSize: 10485760

server:
  port: 17711

